#!/usr/bin/env php
<?php

if (strtolower(php_sapi_name()) !== 'cli') die('This is a Command Line Application!');

use ManagementSystem\Actions;

require_once __DIR__.'/vendor/autoload.php';

if (isset($argv[1]) && strpos($argv[1], '--action=') === 0) {
    $action = explode('=', $argv[1])[1];

    switch ($action) {
        case 'add':
            Actions::add();
            break;

        case 'edit':
            if (isset($argv[2]) && strpos($argv[2], '--id=') === 0 && isset($argv[3]) && strpos($argv[3], '--type=') === 0) {
                return Actions::edit(explode('=', $argv[2])[1], explode('=', $argv[3])[1]);
            }

            echo "Missing --id or --type" . PHP_EOL;

            break;

        case 'delete':
            if (isset($argv[2]) && strpos($argv[2], '--id=') === 0) {
                return Actions::delete(explode('=', $argv[2])[1]);
            }

            echo "Missing --id" . PHP_EOL;

            break;

        case 'search':
            if (isset($argv[2]) && strpos($argv[2], '--keyword=') === 0) {
                return Actions::search(explode('=', $argv[2])[1]);
            }

            echo "Missing --search or --keyword" . PHP_EOL;

            break;

        default:
            echo "Invalid action!" . PHP_EOL;
            break;
    }

    return;
}

echo "Student management system

Usage:
    command [options] [arguments]

Options:
    --action:
        add     Add student
        edit    Edit student
        delete  Delete student
        search  Search students using keywords

Arguments:
    --id        php system --action=edit --id=0000001
                php system --action=delete --id=0000001
    --keyword   php system --action=search --keyword=cliff
";
